#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql:///catchyou
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9100
spring:
  application:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.132.37.81:3306/Camp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.catchyou.pojo
