server:
  port: 9100
spring:
  application:
    name:  ByteDanceCamp
  datasource:
    url: jdbc:mysql://localhost:3306/catchyou
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.catchyou.pojo
  configuration:
    map-underscore-to-camel-case: true
