server:
  port: 9100
spring:
  application:
    name:  ByteDanceCamp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
#    url: jdbc:mysql://1.15.154.78:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 112.74.41.146
    port: 6379
    password: h0vnixnqlpGDX@Ue
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.catchyou.pojo
  configuration:
    map-underscore-to-camel-case: true
